### ISSUE TITLE
Add JSON as a output format

### ISSUE THREAD

**Issue by seifreed** [dhondta/malicious-macro-tester#2]
The tool have now support to:

- MD
- HTML
- PDF
- TXT
Could be possible add support to JSON?

**Comment by dhondta** [comment]
Thank you for posting this enhancement proposal.
I will work on it soon. I let you know.

**Comment by seifreed** [comment]
Nice!

Can't wait for it!

**Comment by dhondta** [comment]
This should be fine now.
