### ISSUE TITLE
Support store the results in ElasticSearch?

### ISSUE THREAD

**Issue by seifreed** [dhondta/malicious-macro-tester#6]
If you process hundreds of files and as the tool already has support to JSON, could be cool have support elasticsearch to store the results there

**Comment by dhondta** [comment]
I will look at this soon.
Note that I currently have no ElasticSearch node running, so it will be difficult to test.

**Comment by seifreed** [comment]
You can download elasticsearch and execute it locally to do any test!

Let me know if you need any clarification

**Comment by dhondta** [comment]
Still to be tested...

**Comment by seifreed** [comment]
Can i test this?

**Comment by dhondta** [comment]
Of course, you can...
